/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectojuegos;

/**
 *
 * @author GABRIEL-PC
 */
public class Nadadores extends javax.swing.JFrame {

    /**
     * Creates new form Nadadores
     */
    public Nadadores() {
        initComponents();
        Invisibles();
    }
    public  void Invisibles() {
        PrimerNadador.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        SegundoNadador = new javax.swing.JButton();
        Jugauno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PrimerNadador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PrimeroA = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel6.setText("jLabel2");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosandPersonas/jasjdasjdaksd.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imagenkk3.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosandPersonas/2pvvmuliq533q_normal_face.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 75, 70, 110);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosandPersonas/23yqs5ns6d83v_normal_face.png"))); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 200, 60, 105);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosandPersonas/22jw86m97nt1q_normal_face.png"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(110, 200, 60, 105);

        SegundoNadador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosandPersonas/asas.png"))); // NOI18N
        SegundoNadador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SegundoNadador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoNadadorActionPerformed(evt);
            }
        });
        jPanel1.add(SegundoNadador);
        SegundoNadador.setBounds(100, 80, 70, 105);

        Jugauno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosandPersonas/3s1gd20o1l4tm_normal_face.png"))); // NOI18N
        Jugauno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jugauno.setDefaultCapable(false);
        Jugauno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Jugauno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugaunoActionPerformed(evt);
            }
        });
        jPanel1.add(Jugauno);
        Jugauno.setBounds(20, 80, 70, 105);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imgaenkk5.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 80, 90, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imagenkk4.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 190, 60, 60);

        PrimerNadador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/Sin título.png"))); // NOI18N
        jPanel1.add(PrimerNadador);
        PrimerNadador.setBounds(440, 240, 50, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imgaenkk5.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 30, 80, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imagenkk1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 330, 70, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imagenkk1.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 130, 70, 63);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/Sin título.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(440, 480, 53, 36);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imagenkk3_1.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(440, 280, 80, 50);

        PrimeroA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imagenkk3_1.png"))); // NOI18N
        PrimeroA.setText("jLabel4");
        jPanel1.add(PrimeroA);
        PrimeroA.setBounds(440, 40, 50, 90);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imgaenkk5.png"))); // NOI18N
        jLabel12.setText("jLabel4");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(430, 290, 80, 90);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nadadores/imagenkk4.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(440, 410, 70, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosandPersonas/jasjdasjdaksd.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 10, 550, 561);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 1079, 694);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JugaunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugaunoActionPerformed
      Jugauno.setVisible(true);
    }//GEN-LAST:event_JugaunoActionPerformed

    private void SegundoNadadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoNadadorActionPerformed
      SegundoNadador.setVisible(true);
    }//GEN-LAST:event_SegundoNadadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nadadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nadadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nadadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nadadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nadadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jugauno;
    private javax.swing.JLabel PrimerNadador;
    private javax.swing.JLabel PrimeroA;
    private javax.swing.JButton SegundoNadador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
