
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author keilor
 */
public class juego2 extends javax.swing.JFrame {
    private int columnas = 8;
    private int filas = 5;
    private int personajecolumnas = 0;
    private int personajefilas = 0;
    public static final int tamañocuadro = 60;
    
    
    
    //Matriz logica
    private int [] [] logica = new int [columnas] [filas];
    // matriz grafica
    private JLabel [] [] grafica = new JLabel [columnas] [filas];
    
    
    

    /**
     * Creates new form juego2
     */
    public juego2() {
        initComponents();
        nuevamatriz();
        mostrarmatrizpanel();
    }
    
    private void nuevamatriz(){  // hacer la matriz temporal de modo aleatorio 
        int [][] temp = {{3,(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1)},
                {(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1)},
                {(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1)},
                {(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1)},
                {(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1)},
                {(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1)},
                {(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1)},
                {(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1),(int)(Math.random()*2+1)},
                
                
            
        };
        logica = temp;
        
        
    }
    private void mostrarmatrizpanel(){
        for(int i=0;i<columnas;i++){ 
            for(int j=0;j<filas;j++){
                grafica [i][j] = new JLabel();//para motrar en la grafica
                grafica [i][j].setOpaque(true);// para poder motrar
                grafica [i][j].setBounds((i*tamañocuadro)+30, (j*tamañocuadro)+30, tamañocuadro, tamañocuadro);// definir tamaño del cuadro y la posicion 
                grafica [i][j].setVisible(true);
                grafica [i][j].setBackground(Color.red);//color del cuadro
                grafica [i][j].setIcon(imagenenmatriz(logica[i][j]));
                jppanelprincipal.add(grafica[i][j]);
                //
            }
        }
    }
    
    private ImageIcon imagenenmatriz(int tipo){
        switch(tipo){
            case 2:
                return new ImageIcon(getClass().getResource("/Imageneskeilor/pared.jpg"));
            case 3:
                return new ImageIcon(getClass().getResource("/Imageneskeilor/6.png"));
            
           default: 
               return new ImageIcon(getClass().getResource("/Imageneskeilor/03.jpg"));
    
                
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respuestas = new javax.swing.ButtonGroup();
        jppanelprincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("PREGUNTA???????????");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        respuestas.add(jRadioButton1);
        jRadioButton1.setText("Verdadero");

        respuestas.add(jRadioButton2);
        jRadioButton2.setText("Falso");

        jButton3.setText("Aceptar");

        javax.swing.GroupLayout jppanelprincipalLayout = new javax.swing.GroupLayout(jppanelprincipal);
        jppanelprincipal.setLayout(jppanelprincipalLayout);
        jppanelprincipalLayout.setHorizontalGroup(
            jppanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppanelprincipalLayout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addGroup(jppanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppanelprincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppanelprincipalLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppanelprincipalLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(89, 89, 89))))
        );
        jppanelprincipalLayout.setVerticalGroup(
            jppanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppanelprincipalLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jppanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jppanelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jppanelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juego2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel jppanelprincipal;
    private javax.swing.ButtonGroup respuestas;
    // End of variables declaration//GEN-END:variables
}
